version: "3.8"

services:


  postgres:
    image: postgres:15
    container_name: crawler-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: crawler-redis
    restart: always
    ports:
      - "6379:6379"


  backend:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/scraper-backend:${TAG}
    container_name: backend
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - postgres


  worker:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/scraper-crawler:${TAG}
    container_name: crawler-worker
    command: node worker/worker.js
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
      - postgres

  scheduler:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/scraper-crawler:${TAG}
    container_name: crawler-scheduler
    command: node scheduler/scheduler.js
    environment:
      NODE_ENV: ${NODE_ENV}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
      - postgres


  nginx:
    image: 529646246979.dkr.ecr.ap-southeast-2.amazonaws.com/scraper-nginx:${TAG}
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data: